import { Trip, Accommodation, TripEvent } from '@/types/trip'

export const sampleTrip: Trip = {
  id: 'florida-2026',
  name: 'Florida Family Reunion 2026',
  startDate: '2026-07-04',
  endDate: '2026-07-12',
  location: 'Gulf Coast, Florida',
  description:
    'Annual family reunion on the beautiful Florida Gulf Coast. Sun, sand, seafood, and family fun!',
}

export const sampleAccommodations: Accommodation[] = [
  {
    id: 'acc-1',
    tripId: 'florida-2026',
    name: 'Beachfront House – The Main House',
    address: '1234 Gulf Blvd, Clearwater Beach, FL 33767',
    lat: 27.9778,
    lng: -82.8277,
    checkIn: '2026-07-04',
    checkOut: '2026-07-12',
    guests: ['Jon', 'Sarah', 'Kids'],
    bookingUrl: 'https://www.vrbo.com',
  },
  {
    id: 'acc-2',
    tripId: 'florida-2026',
    name: 'Beach Cottage – The Annex',
    address: '5678 Sand Dollar Dr, Indian Rocks Beach, FL 33785',
    lat: 27.8907,
    lng: -82.8468,
    checkIn: '2026-07-04',
    checkOut: '2026-07-10',
    guests: ['Uncle Mike', 'Aunt Linda', 'Cousins'],
    bookingUrl: 'https://www.airbnb.com',
  },
  {
    id: 'acc-3',
    tripId: 'florida-2026',
    name: 'Condo – The Overflow',
    address: '910 Gulf Way, St. Pete Beach, FL 33706',
    lat: 27.7255,
    lng: -82.7406,
    checkIn: '2026-07-05',
    checkOut: '2026-07-12',
    guests: ['Grandma', 'Grandpa', 'Aunt Patty'],
  },
]

export const sampleEvents: TripEvent[] = [
  {
    id: 'evt-1',
    tripId: 'florida-2026',
    title: '✈️ Everyone Arrives',
    date: '2026-07-04',
    location: 'Tampa International Airport',
    description: 'Arrivals all day — welcome to Florida!',
    type: 'transport',
  },
  {
    id: 'evt-2',
    tripId: 'florida-2026',
    title: '🎆 4th of July Beach Party',
    date: '2026-07-04',
    endDate: '2026-07-05',
    location: 'Clearwater Beach',
    description: 'Cookout, fireworks, and beach volleyball.',
    type: 'activity',
  },
  {
    id: 'evt-3',
    tripId: 'florida-2026',
    title: '🐠 Snorkeling Trip',
    date: '2026-07-05',
    location: 'Fort De Soto Park',
    description: 'Guided snorkel tour — sign up by July 1!',
    type: 'activity',
  },
  {
    id: 'evt-4',
    tripId: 'florida-2026',
    title: '🦈 Clearwater Marine Aquarium',
    date: '2026-07-06',
    location: 'Clearwater Marine Aquarium',
    description: 'Home of Winter the dolphin. Great for kids!',
    type: 'activity',
  },
  {
    id: 'evt-5',
    tripId: 'florida-2026',
    title: '🦞 Family Seafood Dinner',
    date: '2026-07-06',
    location: 'Frenchy\'s Rockaway Grill, Clearwater Beach',
    description: 'Group reservation at 7 PM. Fresh Gulf seafood!',
    type: 'meal',
  },
  {
    id: 'evt-6',
    tripId: 'florida-2026',
    title: '⛵ Sunset Sailboat Cruise',
    date: '2026-07-07',
    location: 'Clearwater Marina',
    description: 'Two-hour sunset cruise — bring sunscreen!',
    type: 'activity',
  },
  {
    id: 'evt-7',
    tripId: 'florida-2026',
    title: '🏖️ Free Beach Day',
    date: '2026-07-08',
    location: 'Caladesi Island State Park',
    description: 'No agenda. Just sun, water, and good vibes.',
    type: 'activity',
  },
  {
    id: 'evt-8',
    tripId: 'florida-2026',
    title: '🎳 Family Game Night',
    date: '2026-07-09',
    location: 'The Main House',
    description: 'Board games, cards, and friendly competition.',
    type: 'activity',
  },
  {
    id: 'evt-9',
    tripId: 'florida-2026',
    title: '🌅 Sunrise Kayaking',
    date: '2026-07-10',
    location: 'Weedon Island Preserve',
    description: 'Early morning paddle through the mangroves.',
    type: 'activity',
  },
  {
    id: 'evt-10',
    tripId: 'florida-2026',
    title: '🍕 Final Farewell Dinner',
    date: '2026-07-11',
    location: 'The Clearwater Beach Hotel Rooftop',
    description: 'Last supper together — making memories!',
    type: 'meal',
  },
  {
    id: 'evt-11',
    tripId: 'florida-2026',
    title: '🏠 Checkout & Departures',
    date: '2026-07-12',
    location: 'Tampa International Airport',
    description: 'Safe travels home, everyone!',
    type: 'transport',
  },
]
